name: poeta_auth0_client
description: A new Flutter library for Poeta Digital can apply Auth0 as soon as possible.
version: 0.1.0
homepage: https://github.com/andoutica/poeta_auth0_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  rxdart: ^0.22.0
  http: ^0.12.1
  flutter_appauth: ^0.9.2+3
  flutter_secure_storage: ^3.3.3
  shared_preferences: ^0.5.10
  connectivity: ^0.4.9+2
  jwt_decoder: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
